testing publishing

diff --git a/.github/workflows/gradle-publish-base.yml b/.github/workflows/gradle-publish-base.yml
--- a/.github/workflows/gradle-publish-base.yml
+++ b/.github/workflows/gradle-publish-base.yml
@@ -71,19 +71,65 @@ jobs:
             **/wff-validator.jar
             **/wff-xsd.zip
 
-  publish_package:
+  publish_packages:
     runs-on: ubuntu-latest
     needs: build_memory_footprint
     env:
       GH_TOKEN: ${{ github.token }}
+    strategy:
+      matrix:
+        jar_file: [wff-validator.jar, memory-footprint.jar]
     steps:
       - name: Install GitHub CLI
         run: |
           sudo apt-get update
           sudo apt-get install gh
-      - name: Download all assets
+      - name: Download asset
         run: |
-          gh release download --repo "$GITHUB_REPOSITORY" --pattern "*.jar" 
-      - name: Verify download
+          gh release download --repo "$GITHUB_REPOSITORY" --pattern {{ matrix.jar_file }} 
+      - name: Get JAR version
+        id: get_version
         run: |
-          ls -l
+          VERSION=$(unzip -p ${{ matrix.jar_file }} META-INF/MANIFEST.MF | grep "^Version: " | cut -d' ' -f2)
+          if [[ -z "$VERSION" ]]; then
+            echo "::error file=${{ matrix.jar_file }}::Could not determine version from JAR's Manifest file"
+            exit 1
+          fi
+          echo "::set-output name=version::$VERSION"
+      - name: Determine final version
+        id: final_version
+        run: |
+          VERSION="${{ steps.get_version.outputs.version }}"
+          if ${{ inputs.release_name == 'latest' }}; then
+            VERSION="$VERSION-SNAPSHOT"
+          fi
+          echo "Final version: $VERSION"
+          echo "::set-output name=final_version::$VERSION"
+
+      - name: Determine artefact name
+        id: artefact_id
+        run: |
+          FILE_NAME="${{ matrix.jar_file }}"
+          FILE_NAME_WITHOUT_EXTENSION="${FILE_NAME%.*}"
+          echo "::set-output name=artefact_id::$FILE_NAME_WITHOUT_EXTENSION"
+  
+      - name: Publish to GitHub Packages
+        run: |
+          mvn deploy:deploy-file \
+            -DgroupId=com.google.watchface \
+            -DartifactId=${{ steps.artefact_id.outputs.artefact_id }} \
+            -Dversion=${{ steps.final_version.outputs.final_version }} \
+            -Dpackaging=jar \
+            -Dfile=${{ matrix.jar_file }} \
+            -Durl=https://maven.pkg.github.com/google/watchface \
+            -DrepositoryId=github -s ~/.m2/settings.xml
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: create settings.xml
+        run: |
+            mkdir -p ~/.m2
+            echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ github.event.inputs.repo_token }}</password></server></servers></settings>" > ~/.m2/settings.xml
+        shell: bash
+        env:
+          GITHUB_PATH: ~/.m2/
